### ISSUE TITLE
A ment based starting kit

### ISSUE THREAD

**Issue by curiousdannii** [i7/kerkerkruip#256]
An idea for a new starting kit: a ment based one. Possibly it would give you more packages of ment, and at least one ment dependant item.

Is ment set up for more than three addiction levels?

**Comment by curiousdannii** [comment]
@VictorGijsbers Did you end up starting to work on this? If we don't decide to complete this, anything you've done already should temporarily be commented out for version 10.

**Comment by VictorGijsbers** [comment]
Not sure, but I'll look into it.

**Comment by mciul** [comment]
I'm pretty sure I included this when I worked on https://github.com/i7/kerkerkruip/issues/359

**Comment by rvdpluijm** [comment]
I've seen it already:

https://github.com/i7/kerkerkruip/blob/master/Kerkerkruip.materials/Extensions/Victor%20Gijsbers/Kerkerkruip%20Start%20and%20Finish.i7x#L865

**Comment by mciul** [comment]
It definitely works. I even have some tests related to it, all of which are passing. Victor, I think you can close this ticket!

**Comment by VictorGijsbers** [comment]
Done!
