### ISSUE TITLE
Chain golem's picture has eyes

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#276]
I love the card for the chain golem, but I just noticed it has eyes even though the chain golem is eyeless. Now, I think you could argue that the eyes in the picture are just decorative, but there is nothing in the chain golem's text that says it is eyeless. I wonder if perhaps a message should be shown in every eyeless creature's description so nobody gets confused and wastes flash grenades on them.

**Comment by VictorGijsbers** [comment]
Closing this with the assumption that my wiki-suggestion is a good one. (And can be followed up on in the future.) If anyone disagrees, please re-open and re-schedule for a future version.
