### ISSUE TITLE
Random Seeds

### ISSUE THREAD

**Issue by VictorGijsbers** [i7/kerkerkruip#308]
One thing I love about Brogue are the seeded competitions. Basically, someone announces a seed on the forum, and everybody then starts a game with that random seed. That means everyone plays the same game, and you can compare how far you got and what strategies you used.

If possible, I'd like to add the option to start a game with a specific seed to Kerkerkruip. A seed should probably consist of (a) a number indicating the difficulty level, and (b) a random seed. So if you enter "227893" you would start a game on difficulty level 2 with random seed 27893.

Would this just work in Inform 7? Can we seed the random generator at run-time? Kerkerkruip does build the entire dungeon at once, so I see no problem in that regard.

**Comment by VictorGijsbers** [comment]
Is this stuff working? If not, is it easy to get to work, or do we need to comment out the option from the main menu and reschedule this for Kerkerkruip 11?

**Comment by curiousdannii** [comment]
It was kind of working, but I wasn't convinced it was safe. Let's postpone it.

**Comment by mciul** [comment]
If I remember correctly, I've been using this in my automated tests. I'd be happy to close it, but postponing is fine too.

**Comment by curiousdannii** [comment]
The dungeon generation is working fine. The part I wasn't sure about was the cross-version checks - we were thinking that it might be safe to use the same seed across minor updates (10 - 10.0.1) if those updates didn't change anything that would affect generation. I don't think I made that reliable enough.

But thinking about it now, do we need that at all? Why don't we just tell people to ensure they only use it in the same version of the game, and if they do use a seed in the wrong version, then that will be up to them to notice.

**Comment by mciul** [comment]
Sounds good to me.

**Comment by VictorGijsbers** [comment]
OK, but let's leave it open -- I'd like to test it before we ship with it. ;-)
