### ISSUE TITLE
Retreating when followed

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#310]
I've discovered a little loophole that is useful but not satisfying.

If someone follows you into the room (especially the Reaper, who doesn't follow you every turn), you can "retreat" to the room they just came from. This is really useful if it happens right after you saw the Reaper in an unexplored room - it means you can escape past him to a new area of the dungeon.

I kind of think this should be changed, but it would require a big change to the way retreating works now. Intuitively, you should be able to retreat to any place EXCEPT the one you both came from. Plus, if there was already someone in the room gone to, retreating might become completely impossible.

How do you think this should work?

**Comment by VictorGijsbers** [comment]
Personally, I'm fine with this behaviour. Just think about it this way: you retreat, hide behind the door, the Reaper follows you, and you slip past him back to the part of the dungeon that he was originally guarding. Sounds good to me. :-) Reworking the retreat code sounds like it would be a lot of work for minimal (if any) benefits. Mike, do you feel strongly about this? If not, we can close it; if you do, let's have a discussion, but I'm scheduling that for Kerkerkruip 11.

**Comment by mciul** [comment]
I do not feel strongly about it.
