### ISSUE TITLE
Overriding damage

### ISSUE THREAD

**Issue by VictorGijsbers** [i7/kerkerkruip#320]
When a weapon deals damage not based on its physical material (e.g., the staff of pain dealing necromantic damage), we should make sure that concentration and offensive flow add to the necromantic damage, not the physical damage. I need to add an overriding damage type to make this happen.

**Comment by mciul** [comment]
I missed this issue when linking #378. There is some duplication between them.

I was just thinking about my "cutting/piercing/blunt" problem and I think I realized why I was hung up on it. "Physical damage" doesn't really mean "tangible damage" - it means *kinetic* damage. It's not a problem with the code, it's a problem with my interpretation of the words. If there ever is a case where we need to make a distinction between physical as in physics and physical as in forceful contact, we can use the words "tangible" and "kinetic."

**Comment by VictorGijsbers** [comment]
I can't remember exactly what was going on here, but it seems that what I wanted to achieve in the first post is already achieved using the notion of primary damage. (For instance, if you use the staff of pain, all tension and concentration damage is counted as necromantic.) If a problem is found, it would probably be better to open a new issue anyway, since this one is kind of confusing.
