### ISSUE TITLE
Wisps of pain too hard to damage now?

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#345]
Now that we have the new damage system, fragmentation grenades don't work on the wisps of pain - ever! I don't think scrolls of death would do anything to them either. I think that makes them a little too tough for a level 1 monster... although I guess you could argue that their inability to do damage keeps them out of level 2. What do you think about reducing their health a little, or changing their damage reduction to 4 instead of 5?

**Comment by VictorGijsbers** [comment]
Closing this for now; reopen when/if needed.
