### ISSUE TITLE
Return of maze bug

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#358]
> n
You move through the tunnels, quickly losing all sense of direction.

Maze
You are in a maze of twisty little passages, all alike. Exits lead in all directions.

A ferocious minotaur wielding a big axe stands ready for combat.

With a fearsome bellow, the minotaur swings at you.
Just when I thought these bugs are dead, they're back again. I've been messing around with arena code, so I probably broke something. Which reminds me, I haven't run the full suite of tests in a while.

The only related bug I could find: #264
```
React> c
You concentrate, and are now mildly concentrated.

Rolling 5 - 2 (the large minotaur’s axe penalty) + 2 (inherent bonus) - 3 (random body bonus) - 1 (defender small) + 3 (minotaur’s axe stronger in the maze) - 1 (your defence increased by ment) = 3, the minotaur 
does not overcome your defence rating of 8.
```

**Comment by mciul** [comment]
You know, I just read that wrong. There's no bug! Can you delete issues?

**Comment by curiousdannii** [comment]
[Apparently not.](https://github.com/isaacs/github/issues/253) But it doesn't matter. I'll mark this as invalid.
