### ISSUE TITLE
Aite damage (and other gods?)

### ISSUE THREAD

**Issue by VictorGijsbers** [i7/kerkerkruip#361]
I just fixed how Aite's spike text looks, but in fact it's working wrong. It first prints the damage, then calls the damage system to potentially reduce the damage. I need to change this.

**Comment by mciul** [comment]
I just saw your comment on #360 and was confused that Aite spike damage bypasses the damage system. I hope that doesn't have to be true.

By the way, I love it when you show up and start commenting on all the recent issues. Yay!

**Comment by VictorGijsbers** [comment]
No, I think I was wrong about the Aite spikes. They don't bypass the damage system, but they print their message /as if/ they do so. It's the message that needs to change. :-)

And I also love it when I find the time to show up and start doing things! Thanks for all the work you did in the meantime.

**Comment by mciul** [comment]
Wasn't there some stuff in the old Aite spike code about "pdr?" I thought the Aite damage was physical, not divine. As it stands now, it looks like it would be possible to reduce Aite damage, but the damage amount shown would not reflect the reduction.

I wouldn't mind rewriting the phrase if that was required. Although it looks like the damage-material would vary between wood and iron if it were faithful to the current text...

**Comment by mciul** [comment]
I think this works now - I forgot about this issue but covered some aspects of it in #414. I just added a test, which produces this output:

```
A huge pike bursts out of the ground, skewering the healer of Aite for 3 - 3 (testing divine damage reduction) = 0 damage!
```

A little clunky-looking, but it demonstrates that Aite damage can be reduced. I'm going to leave it as divine damage for simplicity's sake.

**Comment by VictorGijsbers** [comment]
Great!
