### ISSUE TITLE
Should Drakul drink blood from non-flesh enemies?

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#365]
I am having an awesome game with Cthon favour, Drakul, and power of the overmind. Drakul is an amazing ally! But I wonder if he's a little too amazing when he drinks the blood of the swarm of daggers. Maybe that should only work on creatures made of flesh...

**Comment by VictorGijsbers** [comment]
Good point. Logically, that's right. Would the same hold for the vampiric dagger? Could either work against an undead made of flesh, like the zombie toad?

**Comment by mciul** [comment]
Another good point! I think I would say both should fail against any nonflesh opponent. I could go either way against undead, but if I had to choose, I would say that should also fail.
