### ISSUE TITLE
Killing rules problems

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#369]
I still seem to be having a million problems with killing rules. I'm including a whole transcript this time: https://gist.github.com/mciul/3a11655dd5802fd51716

Twice during this game, I killed a monster (minotaur and chain golem) and inexplicably did not absorb its soul. Once, I got healed, but still didn't get the creature's power. I have no idea why.

**Comment by mciul** [comment]
Right before I started this game I ran all the automated tests. I wonder if the tests left some things out of order.

**Comment by VictorGijsbers** [comment]
I'm closing this, since it appears we don't know whether the automated tests might be responsible. If we notice this stuff happening again, we can reopen the issue, or make a new one.
