### ISSUE TITLE
Are daggers too powerful?

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#374]
The more I play Kerkerkruip, the more I favor daggers. I wasn't really thinking of this a problem, but yesterday when I was trying out Automatos, I managed a major hit quite easily with a dagger, and it said "The impact of the attack is so great that Automatos stagggers backwards and shakes his head several times." The text seemed incongruous with a dagger, and it got me thinking... the tension bonus makes sense for the attack strength of a dagger, but does it really make sense for the damage? We have the executioner's axe for that. What if we just did away with it? I think even without it daggers would be great weapons. We could maybe give them a higher damage die, or keep the tension damage bonus but have it max out at 3.

Or, here's another idea that would work for Automatos: give daggers a damage penalty against metal defenders. Too complicated?

**Comment by mciul** [comment]
My current thought is to completely remove the tension damage bonus for daggers. I still think they would be good. There would be fewer sources of big damage, which would make the wisps of pain and healing monsters harder to beat. But I think fixing that would make the game more balanced.

**Comment by mciul** [comment]
I just looked back at this. I have reduced the dagger tension damage bonus and daggers still seem to be better than axes for damage in the games I have played. I think I'm ready to get rid of the dagger tension damage bonus completely.

**Comment by VictorGijsbers** [comment]
Maybe we should try this: remove tension damage bonus from daggers, as you suggest; add 1 damage to axes; give swords a 50% chance of adding 1 extra defensive flow after a successful parry. We could try the +1 parry bonus, but I'm afraid it might be too good. (1 extra point of defence is quite strong, and sword aren't bad.) What do you think?

**Comment by mciul** [comment]
I will give that a try.

**Comment by mciul** [comment]
The gilded rapier is not a sword. Now I don't know a lot about swords, so maybe that makes sense. But do you think it should get the same defensive flow bonus from parrying as swords?

**Comment by mciul** [comment]
I think this is all done but the playtesting.

**Comment by VictorGijsbers** [comment]
Yes, you can certainly parry with a rapier. Let's give it the same bonus. In fact, let's make it a sword (but with the same stats it has now).

**Comment by mciul** [comment]
I'm really happy with this.
