### ISSUE TITLE
General and specific damage can't be added if original damage was 0

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#378]
Related to: #354 #360 #319 #320

I'm going for complete code coverage for every invocation of "inflict," so I can be sure I don't break anything when I work on #360. The tentacle has two common attack damage messages, and I'd like to make sure I see both of them. Unfortunately, I'm not sure about the circumstances in which they can happen. I could have sworn I saw a case where the tentacle does 1 damage when attacking, but I can't figure out how that happened and I can't reproduce it now.

In addition, while I was investigating this, I found a troubling case. The "inflict" phrase runs the "before damage rules" and then checks if the total harm of all types is 0. If it is, the phrase assumes that all damage was canceled and exits.

However, in the case of the tentacle, the original damage was 0, even though nothing was canceled. This means that specific and general damage (e.g. concentration and tension) are never applied. I don't think this is right, but I don't remember what happened before (I wish I'd written the tests earlier!)

This does not look easy to fix. Please help me figure out what to do!

After looking at the code, it appears that the whole point of the pre-check is to circumvent the add general damage rules when there is a damage immunity. That seems like a good argument for eliminating the add general damage rulebook completely. All of the existing rules but one concern attack damage. Except for the staff of pain, attack damage is always physical. Here's my proposal:

* eliminate the add general damage rules
* create a variable to hold the attack damage type. We could even add a null damage type, and set the attack damage to it instead of setting damage-by-hitting to false.
* All damage-by-hitting rules (maybe that should be a rulebook) increase the harm of the attack damage type, instead of assuming it is physical.
* Concentration and tension should have add specific damage rules, not add general damage rules, and they should increase the harm of the attack damage type.
* Damage immunity can now be placed in specific damage multiplier rules. Unless you're worried about a flaming staff of pain doing undeserved damage to undead...

After attack modifiers are eliminated, only one add general damage rule remains: the death curse. I'm sure we can come up with a way to handle that.

**Comment by mciul** [comment]
I think this can be generalized a little more. Instead of the attack damage type, the variable could be called the primary damage type. By default, primary damage will be set to physical damage, but it can be reset manually. The before damage rules would be a good place to do this, and in fact it is where the staff of pain converts physical to necromantic damage. I propose a phrase to do this:

```
to convert (old damage - a damage type) to (new damage - a damage type):
    now the harm of new damage is the harm of new damage + the harm of old damage;
    now the harm of old damage is 0;
    if old damage is primary damage, now primary damage is new damage.
```

Then all add "add general damage" rules could be "add specific damage" rules that affect primary damage. This still leaves the death curse - should it add primary damage or necromantic damage? Either way, it is a change that will allow the damage to be reduced. Is that bad?

**Comment by VictorGijsbers** [comment]
Mike, great that you are working on this! (And so much other tests as well.) I need to look into this a bit more deeply, perhaps somewhere in the next two days!

**Comment by mciul** [comment]
What can I say, I'm obsessed!

**Comment by mciul** [comment]
Here's another question that's relevant to damage immunity: when piercing with the staff of pain, is the piercing damage physical or necromantic? Or is piercing even relevant to ranged weapons?

**Comment by mciul** [comment]
Whew! That's it! I've written tests for every damage modifier rule that can run!

Now I'm actually ready to refactor...

**Comment by mciul** [comment]
I've slept on this, and I've decided that the smoke demon loses. Getting rid of add general damage rules will make everything simpler, and if the smoke demon needs a boost, it can have a little extra health or the density multipliers can be reduced.

My bigger concern right now is that it makes daggers even more powerful. I'm planning to have a look at #374 next.

**Comment by mciul** [comment]
Oh dear, I found an unexpected side effect of this change...

If the tentacle attacks and does 0 damage, it gets a +2 damage bonus for its size. Being one of the weakest level 3 creatures, maybe this isn't bad, but I did like the style of the tentacle doing no damage during the attack. Here's some changes I'd consider:

* give the tentacle a -2 inherent damage modifier
* make the tentacle's natural weapon size-agnostic
* give the tentacle some extra health
* make the tentacle's "confuse" reaction more powerful
