### ISSUE TITLE
Balancing the tentacle

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#379]
Spawned from #378... changes to the damage system cause the tentacle to do more damage than it was doing. This is actually damage that it did in Kerkerkruip 9, so maybe there's not that much to discuss. But here's what I was thinking:

If the tentacle attacks and does 0 damage, it gets a +2 damage bonus for its size. Being one of the weakest level 3 creatures, maybe this isn't bad, but I did like the style of the tentacle doing no damage during the attack. Here's some changes I'd consider:

* give the tentacle a -2 inherent damage modifier
* make the tentacle's natural weapon size-agnostic
* make the tentacle's natural weapon do 1d2-1 damage
* give the tentacle some extra health
* make the tentacle's "confuse" reaction more powerful

Now that I realize all this stuff was in version 9, I think we can keep all the damage bonuses. I'll rerun some fight tests again to see how this changes things.

**Comment by VictorGijsbers** [comment]
Making the tentacle size-agnostic, or even removing its normal damage entirely, is actually not so bad if we can make it more threatening in some other way! Perhaps a special attack (once you are grappled) where the tentacle doesn't squeeze but slams you into a wall for high damage? We could make it something that happens, say, once every six times or less; but it would add some unpredictable damage dealing capability to the tentacle.

**Comment by VictorGijsbers** [comment]
I'm working on this.

**Comment by mciul** [comment]
I really like this idea, but my fight tests are showing that the tentacle rarely throws opponents. Maybe it happens more for the player, but when I ran 100 fights with the minotaur, it only threw the minotaur 3 times. Against the mindslug, it almost never throws anyone. All the tests I've run so far are with throwing behavior #1, the "linear" style.

It seems like throwing can only happen if someone is grappled for a long time. I was wondering if we should give the tentacle a bonus to staying grappled. What if we raise the target mind roll for the "shake?" One idea I had was to have the "shake" power be very strong when someone is first grappled, then gradually get weaker as the tentacle squeezes harder and gets more tired.

**Comment by VictorGijsbers** [comment]
Hm... I'll definitely take a look at the throwing behaviour. On the one hand, if the tentacle throws too often, it becomes too dangerous. On the other hand, it certainly should throw with a certain regularity... more than 3 times in 100 fights! Great that you're running those tests, but the way. :-)

Can you test how often the shake roll is failed and succeeded? That would be useful data for thinking about how to proceed here. It should evidently become harder to get away from the tentacle once grappled! (Though I'm wondering whether it might be harder for a level 2 player than for a level 3 monster? What happens when you run the fight against the Reaper or the demon of rage?)

**Comment by mciul** [comment]
I'm actually running a test against the Reaper right now! :)

Here are the stats I've gathered on shaking so far.

In 100 fights against the minotaur with throwing behaviour 1, the minotaur died 24 times, was thrown 3 times, remained sharp 25 times, and was confused 52 times. Many of these fights ended with a "fake" maze fight, where the minotaur hit the tentacle and the rest of the fight was calculated by the axe aftereffect.

In 100 fights against the mindslug, with throwing behaviour 1:
the mindslug never died, got confused or thrown, and remained sharp 25 times.
Fafhrd died 5 times, never got thrown, remained sharp 58 times, and was confused 101 times.
Mouser died 5 times, never got thrown, remained sharp 7 times, and was confused 35 times.

**Comment by mciul** [comment]
The Reaper is getting thrown with more regularity. In about 25 fights, he's already been thrown 4 times.

**Comment by VictorGijsbers** [comment]
Great data! Still, even 4 times in 25 fights is not enough. I'll change the throwing rules.

**Comment by mciul** [comment]
I finally finished the Reaper fight test last night. What were you saying about performance tests? The fight tests are really slow... I wonder if there's a memory leak involving stored actions - combat AI uses them regularly, doesn't it?

Anyway, here are the results:

In 100 fights, The giant tentacle was killed 41 times and the Reaper was killed 59 times.
Reaper was thrown 23 times, remained sharp 58 times, was confused 207 times.

**Comment by curiousdannii** [comment]
> What were you saying about performance tests? Was that @curiousdannii ? The fight tests are really slow... I wonder if there's a memory leak involving stored actions - combat AI uses them regularly, doesn't it?

It's probably not that any memory is being leaked, but that the template code is just really inefficient. There are a few low hanging fruit which would make a big difference.

**Comment by mciul** [comment]
Whatever caused the slowdown, the first 25 battles were done in maybe an hour, and the remaining 75 took something like 12 hours.

**Comment by curiousdannii** [comment]
Oh wow, that is much slower than anything I've ever seen. Something must be wrong for sure!
