### ISSUE TITLE
New item: Palimpsest

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#381]
How about a palimpsest that can magically copy one scroll without destroying it?

Reading the palimpsest is like reading a scroll, except the palimpsest becomes blank instead of disappearing completely. Then it can copy a new scroll.

**Comment by VictorGijsbers** [comment]
Does that mean that you have infinite scrolls? That would seem to be far too good!

**Comment by mciul** [comment]
Maybe it is. How about these variations:

* Every time you read the palimpsest, there is a 10% chance that it will be destroyed completely.
* The original scroll is destroyed by copying, but reading the palimpsest only has a 25% chance of erasing it.
* The original scroll is destroyed by copying, but only 50% of the time.
* The original scroll is destroyed by copying, and the palimpsest is never erased, but you can only copy once.

**Comment by VictorGijsbers** [comment]
I'm starting to like this as an epic item. We should make sure that it doesn't reward boring strategies like: after every fight you first write protection on the palimpsest, then read it, then write the blade on the palimpsest, then read that, then write teleportation on it, then enter combat ... once your protection gets hit, you read teleportation and do it all again. That should be impossible.

What about this:
1. Neither the scroll nor the palimpsest ever gets destroyed.
2. In combat, writing something takes several turns.
3. After reading from it, the palimpsest is exhausted. Yo write on in, you need to feed it blood. It functions as a normal blood magic item, so each further use of the palimpsest will cost more blood. This would limit the number of uses.

**Comment by VictorGijsbers** [comment]
I'm going to implement the proposal I made above, we can see whether it works in practice.

**Comment by mciul** [comment]
I like that!

**Comment by VictorGijsbers** [comment]
Done! The blood magic cost might need to be tuned, of course.

Together with a scroll of enchantment, this thing is going to be incredible.

**Comment by mciul** [comment]
Hm... maybe the scroll of enchantment shouldn't be cumulative?

**Comment by VictorGijsbers** [comment]
Or the player who gets this combination is just going to be very lucky. :-) We'll see whether it becomes a problem!

**Comment by aaronr7734** [comment]
I'm not sure if this has already been reported, but when you read from the palimpsest (that word is hard to type), It doesn't actually require you to feed it blood to reactivate.  I was able to reactivate a scroll of protection a few times with no problems or complaints from the palimpsest.
