### ISSUE TITLE
Should diminuendi/crescendi work on shields?

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#382]
I see that shield size is now considered for attack rolls, but the unguentum diminuendi doesn't work on shields. Shouldn't it?

**Comment by VictorGijsbers** [comment]
Yes, I guess it should!

**Comment by mciul** [comment]
That leaves the question of whether changing the size should affect the block bonus.

While I was considering that, I looked at the bastion of faith, which resets its block bonus. Should it be size-agnostic? Should everything made of radiance be size-agnostic?

**Comment by VictorGijsbers** [comment]
So my idea about the size penalty is that it would be very hard to effectively move a shield that is much larger than you are -- for one thing, it would be too heavy -- and very hard to effectively cover yourself with a shield that is much smaller than you are, for obvious reasons.

Perhaps the big shield penalty doesn't make much sense for radiance shields, that is true.

**Comment by mciul** [comment]
I'm going to go with that, but for now only the bulwark of faith will be size-agnostic. If we come up with an effect that can turn something radiant, I might reconsider at that point...

**Comment by mciul** [comment]
I've changed my mind about whether size changes should affect the block bonus - I think it should now.
