### ISSUE TITLE
What does "delete (file)" actually do?

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#383]
I've been using "delete (file)" to get rid of test files once I'm done with them, but I just noticed that it doesn't always seem to do anything. In particular, my code to delete the file of test outcomes after a test is done appears to delete the file successfully, but the file doesn't go away, which can mess up subsequent tests. Is this in line with the expected limitations of the phrase, or is something wrong?

@VictorGijsbers - can you help?

**Comment by curiousdannii** [comment]
I'm pretty sure we only have a delete phrase for save files: https://github.com/i7/kerkerkruip/blob/master/Kerkerkruip.materials/Extensions/Victor%20Gijsbers/Kerkerkruip%20Permadeath.i7x#L82

If you're using the phrase on other files the compiler won't catch it, but I'm surprised you don't get a runtime error.

**Comment by mciul** [comment]
The function takes an argument - it's possible that "SavedGame" is more an indicator of its purpose than a restriction.

**Comment by curiousdannii** [comment]
No, depending on the interpreter, if the file usages don't match then it won't work. Gargoyle seems to always be fine because it doesn't use file extensions (though I'm surprised the runtime system doesn't make a fuss about the mismatched phrase argument.)

**Comment by VictorGijsbers** [comment]
(Let me just note that I don't know anything about this part of Inform. Permadeath was almost wholly written by other people.)

**Comment by mciul** [comment]
I came up with a workaround - I didn't realize that Inform 7 was not designed to be able to delete files easily.
