### ISSUE TITLE
The glass cannon became ineffective

### ISSUE THREAD

**Issue by SplendidFault** [i7/kerkerkruip#384]
The glass cannon, which is the most effective weapon in this game, does not seem to be working as expected. To give an example:
> Rolling 7 + 2 (the glass cannon bonus) + 1 (inherent bonus) - 2 (defender dodging) + 2 (tension) - 1 (incense penalty) = 9, you beat the ravenous armadillo's defence rating of 6.

> You deal 0 + 1 (tension) - 1 (tough scales) = 0 damage, allowing the ravenous armadillo to escape unscathed.

It seems that the die roll of the glass cannon may be  producing the issue:
> Combat statistics: 1d0 + 10 damage; ...

What do you think?

**Comment by mciul** [comment]
Thanks for spotting this. I made some changes to the damage system and this bug probably cropped up then.

**Comment by VictorGijsbers** [comment]
I fixed it! :-)
