### ISSUE TITLE
Can't use TPscrolls

### ISSUE THREAD

**Issue by Fire-Mage-Mai** [i7/kerkerkruip#386]
I have unable to use the Teleportation scrolls to go from town to town it says i need soul points but my soul points are always full. I don't know if you need to be a certain level to use them, which I'm sure isn't the case because i used one when i was a low level or if its glitched but i would like some help please

**Comment by curiousdannii** [comment]
Kerkerkruip doesn't have soul points so I don't know what you were playing, but it can't have been this.

**Comment by Fire-Mage-Mai** [comment]
Sorry I'm new to the site so I might have put this in the wrong spot

**Comment by spinda** [comment]
Were you perhaps looking for [Wynncraft](https://github.com/Wynncraft/Issues)?
