### ISSUE TITLE
Shrinking monster

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#395]
We have a monster that grows, I thought it would be cool to have one that shrinks.

It could be Level 3 or Level 4. It starts out gargantuan, with a high defense rating, and shrinks whenever it is damaged, so it becomes harder and harder to hit. It also gets some other defensive advantage, maybe physical damage reduction.

When you get its power, you shrink too, and get the same defensive advantage. The pdr (or whatever) is a permanent bonus, but you also lose permanent health when you shrink.

I haven't thought of an active ability yet, or how the abilities would interact with faculties.

**Comment by mciul** [comment]
I started work on this: https://github.com/i7/kerkerkruip/tree/angel-of-mercy

**Comment by VictorGijsbers** [comment]
Sounds good! More angels are good too.

**Comment by rvdpluijm** [comment]
Perhaps its active ability could be to be able to (only once per visit per room) attempt to hide again.

**Comment by mciul** [comment]
I had an active ability, but I decided to give it some really cool items instead, so now there is only the passive ability, but you get the Shield of Reflection (reflects ranged attacks) and the Gauntlet of Attraction (steals the attacker's weapon if you parry without a weapon)

Check out the Angel of Mercy! It's more or less done, I'm just tweaking now.
