### ISSUE TITLE
Unknown absorption problem

### ISSUE THREAD

**Issue by VictorGijsbers** [i7/kerkerkruip#397]
I just played a game in which I had two absorption bugs. First, I killed the bomb and nothing happened -- I didn't heal and I didn't get a power. Then, I killed the Repaer, and I got health but no power. I have no idea what was causing this.

Some context: I had killed the overmind, and was walking around with a level 4 power. The overmind had called both the bomb and the reaper. I had teleported the bomb with a grenade. The game contained a mausoleum with Drakul. ... Nothing else comes to mind. I'll keep an eye out for more of this stuff happening!

**Comment by mciul** [comment]
I think I've seen something like this too. I'll be on the lookout now.

**Comment by mciul** [comment]
Do you remember if they were killed during normal combat hits?

**Comment by mciul** [comment]
Here's a transcript with a number of interesting features:

[20160816-1253.txt](https://github.com/i7/kerkerkruip/files/420966/20160816-1253.txt)

It seems to show the absorption bug happening with the chain golem. This was also an overmind game, plus I had just sacrificed a different Level 2 power to Nomos.

I also discovered a few other issues:

If you have an unloaded crossbow and the Nomos bonus goes off, the crossbow fails to fire but the Nomos bonus does not get canceled. I discovered that the only way to get out of the loop was to ready another weapon as a reaction.

Going into a dream with Mercy radiance creates a weird message where the radiance gets canceled in the wrong place. I had the Tungausy dream, and so "the player" was in a different body.

Once you get to tiny size with Mercy power, you stop gaining radiance. I can't remember if I intended that or not. I was disappointed, but maybe it keeps the ability from getting too powerful. What do you think?

**Comment by mciul** [comment]
I bet "now guy accompanies the overmind" has something to do with it:

```
Carry out the overmind overmind-calling:
	let n be potential overmind allies;
	if n is 0:
		say "The overmind attempts to calls its allies, but the machine doesn't seem to function.";
	otherwise:
		if concentration of the overmind is less than 3 or n is 1:
			call an ally;
		otherwise:
			call all allies;
		[ Make overmind allies in the location accompany the overmind ]
		repeat with guy running through all npc alive people in the location of the overmind:
			if level of guy is less than 4 and guy does not oppose the overmind:
				now guy accompanies the overmind;
	now concentration of the overmind is 0.
```

**Comment by curiousdannii** [comment]
Accompanying wasn't originally envisioned for leveled enemies. It was for Mouser and Fafhrd to ensure the Mindslug got their kills.

In this context I think if you're killed by an accompanying leveled enemy both it and its leader get the kill credit.

If you kill a leveled enemy you need to absorb their powers regardless of whether they are accompanying.

When the overmind is killed we should degroup all of its followers because that could have some weird after-effects.

**Comment by mciul** [comment]
Thanks, Dannii. I might look into it over the weekend.

**Comment by VictorGijsbers** [comment]
I'm taking out those lines in the overmind code. Dannii, they come from this commit of yours (long live the new "blame" feature of Github!):

https://github.com/i7/kerkerkruip/commit/15b97ecb5a016f52ecc46e204a7dec9b49e53625

Any idea why they're there? Is it something important?

**Comment by curiousdannii** [comment]
I think I added it so that the kills would be awarded correctly. I think Mike is correct that we should split this system up. There might be some duplicated code, but it would make it all simpler overall, and much safer.

**Comment by VictorGijsbers** [comment]
Do you think we need to work around it for now, to make the kills be counted correctly? (I guess the idea is that these monsters's kills count for the overmind?) Otherwise, let's keep this issue closed.

Mike, can you put the stuff you'd like to do for Kruip 11 as a new issue?
