### ISSUE TITLE
Set test seeds in the noninteractive tests file

### ISSUE THREAD

**Issue by curiousdannii** [i7/kerkerkruip#399]
@mciul:

> One other thing I'd like, though, is to be able to pass a random seed to the automated tests when running noninteractively. If we have the shell script write a number (like the current time) into the file of noninteractive tests, would Inform be able to read it somehow?

Would you like it to be used to set "the initial test random seed"? It shouldn't be too hard to alter that phrase to look for the noninteractivetests file and fall back to using 69 (or whatever) if it the file isn't there or it doesn't have a valid seed.

**Comment by mciul** [comment]
Yes, that's it. It's really useful to keep the seed fixed when diagnosing problems, but a fresh one should be used whenever we just want to see that everything works.

**Comment by curiousdannii** [comment]
@mciul already fixed this :)

**Comment by mciul** [comment]
Thanks for closing this out! I have to add a caveat-- I am still unable to run the "runner" script, so I'm actually using a similar script modified for my system and copying changes over. It would be good for someone else to make sure runner is doing what it's supposed to do.

**Comment by curiousdannii** [comment]
Is that just because of having a different kind of install of Inform 7? I need to make it work with the OSX install...

**Comment by curiousdannii** [comment]
@mciul I haven't tested it, but I think the tools/install-inform7 script will now work on OSX. Let me know if the runner script will work for you now :)

**Comment by mciul** [comment]
Thanks, Dannii! I gave it a try and here's what happened:

```
ciullaptop:kerkerkruip mciul$ make clean
rm -f %.gblorb *.zip
rm -f -r i7 Inform
ciullaptop:kerkerkruip mciul$ make test
curl -L -s -S -O http://inform7.com/download/content/6M62/I7_6M62_Linux_all.tar.gz
mkdir -p Inform/Extensions
curl -L -s -S -O https://github.com/i7/extensions/archive/master.zip
unzip -o -q master.zip
cp -R extensions-master/. Inform/Extensions/
curl -L -s -S -o "Inform/Extensions/Aaron Reed/Numbered Disambiguation Choices.i7x" "http://www.emshort.com/pl/payloads/Aaron%20Reed/Numbered%20Disambiguation%20Choices.i7x"
rm -r extensions-master master.zip
tar -xzf I7_6M62_Linux_all.tar.gz
cd inform7-6M62 && ./install-inform7.sh --prefix ../i7
rm -r I7_6M62_Linux_all.tar.gz inform7-6M62
export HOME=/Users/mciul/git/kerkerkruip; ./i7/libexec/ni --format=ulx --internal ./i7/share/inform7/Internal --noprogress --project "Kerkerkruip.inform"  | grep -Ev "ve also read"
/bin/bash: ./i7/libexec/ni: cannot execute binary file
make: *** [Kerkerkruip.gblorb] Error 1
```

**Comment by curiousdannii** [comment]
To install unbuffer: http://apple.stackexchange.com/a/193152/150485

Deleting noninteractivetests after running the terp and then looping while it exists - very clever! Much simpler than waiting for the proc to finish (and is also cross platform.)

Does the "# Output the full results" section work for you?

if `sed -r` doesn't work then we'll need something else to extract the number of failures from the log. Any ideas?

**Comment by mciul** [comment]
I think the Mac equivalent of the -r option is -E. But how about using perl
instead? I don't know sed very well, so that's what I often do.

I will try some things out and see if I can get it to run without doing
anything I know will fail on Linux...

**Comment by curiousdannii** [comment]
I was thinking very stupidly - of course the OSX won't come with dumb-git, neither does Inform for Gnome!

I was thinking in the future that I may need to make it compile the terp in order to do a profiling build, so I guess I'll make it do this. But making that cross platform will still be tricky...

**Comment by mciul** [comment]
Yes it will! But I've done it on Mac before, so I'd be happy to test what you create.

**Comment by curiousdannii** [comment]
The makefile will now download and install dumb-git. Let me know if you have any trouble!

I've slightly improved the text output. But on Travis your line overwriting code still doesn't work. Not a big problem at all, it's just ugly :P

**Comment by mciul** [comment]
Travis should be considered a non-interactive environment, right? Would it be better not to output any progress information in that case?

**Comment by curiousdannii** [comment]
Yeah that would probably be simplest. Or maybe just a period every minute so that it doesn't time out.

**Comment by rvdpluijm** [comment]
If necessary, I can test this too now (having both Mac (El Capitan) and Linux).

**Comment by mciul** [comment]
dumb-git is fast! Much faster than glulxe, I think! My tests are just zipping by now.
