### ISSUE TITLE
Thorns didn't really break concentration?

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#401]
This looks weird:

```
Act>launch
You raise your hands, and the brambles launch their deadly thorns!

Thorns shoot towards everyone, dealing 1 damage to Malygris (which breaks Malygris's concentration).

Smiling his wicked, slim smile, Malygris lunges towards you.

React>do
You get ready for quick evasive maneuvers.

Rolling 20 - 1 (the dagger of draining penalty) + 7 (inherent bonus) + 8 (concentration) - 2 (defender dodging) - 1 (the dagger of draining dodge bonus) + 2 (tension) + 2 (dagger benefits from tension) - 2 (brambles impede movement) = 33, Malygris beats your defence rating of 14.
```

The thorns message claimed that Malygris's concentration was broken, but he still got a +8 bonus when attacking. I was worshipping Nomos at the time with 2 favour. I'm not sure if any other effects might be involved.

**Comment by rvdpluijm** [comment]
Shouldn't this been taken care of by ATTACK, since "Have the Bramble inflict damage" phrase makes sure the aftereffects rule "breaking concentration" (i.e. An aftereffects rule (this is the alternative lose concentration when hit rule) in Section Losing Concentration) will take effect? I am therefore not certain your solution will not double break the concentration...

**Comment by rvdpluijm** [comment]
@VictorGijsbers, could you take a look at it?

**Comment by mciul** [comment]
Aftereffects rules only run when someone hits someone, not when damage is inflicted.

**Comment by rvdpluijm** [comment]
Ok. Perhaps we should see the brambles as an attack with a critical hit? That should solve the whole issue, shouldn't it?

**Comment by mciul** [comment]
I'm not sure that's necessary - other concentration-breaking effects like fragmentation grenades and waves of death also handle concentration directly. I think the fix I've already implemented will work fine for now.

**Comment by VictorGijsbers** [comment]
Assigning this to myself because I want to check it out. :-)

**Comment by mciul** [comment]
Woooo... exciting! I've been thinking about getting back to this...

**Comment by VictorGijsbers** [comment]
Yep! Although it would be more exciting if I had even the faintest idea how to get the Glimmr stuff to compile...

**Comment by mciul** [comment]
Do we need Dannii for that? I've been wondering if I should try to learn.

**Comment by VictorGijsbers** [comment]
I think we do. I don't know whether he has the time and the inclination to work on it, though. It sure couldn't hurt if more people knew how it worked. ;-)

By the way, where do the tests reside? I made a small prose change which now has one of the travis automated tests fail, and I realised I don't know how to change them.

**Comment by curiousdannii** [comment]
Yeah sorry, I don't really have the time it would take. Not sure I have the interest either to be honest. I'd prefer to move to a JS solution, but that will take a long time too.

**Comment by mciul** [comment]
JS might be slightly less intimidating for me to learn at least. @curiousdannii if you can offer any pointers on how to get started, I might be willing to look into it.

**Comment by mciul** [comment]
@VictorGijsbers the automated test cases are in Extensions/Kerkerkruip/Test Sets.i7x

I'm feeling embarrassed right now about how complicated my testing system is... feel free to ask more questions. :)

**Comment by mciul** [comment]
Btw, what's the url for the Travis report? I don't remember how to find it.

**Comment by VictorGijsbers** [comment]
Related conversation is going on here: https://www.intfiction.org/forum/viewtopic.php?f=4&t=26391

I'm hoping that the Glimmr stuff might be relatively easy to fix, compared to building up an entirely new graphical suite.

When I go to commits and click the red cross, I get this: https://travis-ci.org/i7/kerkerkruip/builds/405052016?utm_source=github_status&utm_medium=notification

**Comment by curiousdannii** [comment]
Another option would be to move to Vorple. We'd have to essentially rewrite all the map making code (the rest would be much easier).

**Comment by mciul** [comment]
Thanks for the links, Victor. If you search in Test Sets for "asdt-dead-beloved," you should find the regular expression mentioned in the error. Changing "pay off" to "pay" should fix the error.
