### ISSUE TITLE
"the" breaks parsing?

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#407]
I found this bug on a Kerkerkruip Let's Play video:

https://www.youtube.com/watch?v=YAwxTFIPGt0

I have confirmed that it happens whenever I refer to something with "the":

```
Entrance Hall
The vast entrance hall is empty, silent, foreboding. Skull-sized rubies project a red light far too bright for the eyes of a human.

You possess three packages of ment, a Morphean grenade, two fragmentation grenades and Metastasio's hat.

You can see a scroll labelled KRIPMETEEL, an unguentum argenti and an ancient papyrus here.

Exits lead north, south, east and down.

>look at unguentum argenti
An expensive alchemical salve that can be rubbed on iron objects to turn them into silver.

>take the salve
You can't see any such thing.


>take salve
Taken.

>take the scroll
You can't see any such thing.
```

Edit: I just checked and I can "take the diadem" - this is probably a problem that only applies to scrolls and some other specific kinds.

Thanks to Remy for discovering this.

**Comment by VictorGijsbers** [comment]
It seems that you can refer to almost nothing with "the". "The rapier," "the me", "the north", "the ment", none of it works. Did we break Inform?

**Comment by VictorGijsbers** [comment]
I've just confirmed that you can refer to everything with "the" in a standard Inform test game, including directions, "me" and items that are of a custom kind. In fact, you can even reiterate "the" with no penalty, e.g., do "x the the the me" and it still works.

Are we interefering with parsing anywhere in our code?

**Comment by VictorGijsbers** [comment]
Also, all of these extensions are innocent (at least, they don't interfere with parsing "the" in a test game):

Include Basic Screen Effects by Emily Short. 
Include version 7 of Numbered Disambiguation Choices by Aaron Reed.
Include version 10/150126 of Glulx Entry Points by Emily Short.
Include version 8/140515 of Dynamic Objects by Jesse McGrew.
Include Questions by Michael Callaghan.
Include version 1/140209 of Interpreter Sniffing by Friends of I7.
Include version 1/140818 of Xorshift by Dannii Willis.
Include version 15/160609 of Flexible Windows by Jon Ingold.
Include version 1/150128 of Menus by Dannii Willis.

**Comment by VictorGijsbers** [comment]
We interfere with parsing in "Going to" of Kerkerkruip UI, in order to read a blank line, but removing that custom code does not fix the problem, so it's probably not causing it.

**Comment by mciul** [comment]
I've found something! Deleting Chapter - Fixing Numbered Disambiguation Choices in Kerkerkruip Ugly Special Cases causes the bug to disappear.

I'm going to dig around to find out if this problem has already been fixed and the code is unnecessary. If it is, I think we should delete this file completely, and move the Armadillo/Drakul's lifeblood thing into Monsters.
