### ISSUE TITLE
Should rotting limbs ever be cursed?

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#410]
I just had a test break because one of the rotting corpse's limbs was cursed. It's sort of an amusing idea, and I wonder if maybe we should allow it, but it was weird for it to be cursed and curse-identified while the corpse was still using it. How do you think this should be handled?

```
**** Failure for test: damage-modifiers, step: limb-removal, assertion 1532: Regular expression "As the corpse reels back from the blow, his rotting " was not found in the text:

"The rotting corpse waits.

Rolling 6 + 100 (inherent bonus) + 2 (corpse missing a leg) = 108, you beat the rotting corpse's defence rating of 50.

You deal 1 + 10 (inherent bonus) = 11 damage, wounding the rotting corpse to 989 health.

As the corpse reels back from the blow, his cursed rotting left arm falls off."
```

**Comment by VictorGijsbers** [comment]
Heh. :-)

I guess we could special-case it, but on the other hand, there's nothing wrong with just leaving it as it is (and of course leaving it as it is is simpler and easier to maintain). That poor rotting corpse must have angered one of the gods, to have them curse his arm!

**Comment by mciul** [comment]
Haha! Ok, let's leave it.
