### ISSUE TITLE
Panels disappear when starting transcript

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#411]
I confirmed that this happens in the release version, not just the testing version where transcripting is automated:
- Start a new game
- make sure panels are on
- > SCRIPT ON
  - panels are gone
- > PANELS
  - `The information panels have been disabled. Type PANELS to re-enable them.`
- > PANELS
  - panels reappear
  - `The information panels have been enabled. Type PANELS to disable them again.`

**Comment by VictorGijsbers** [comment]
That's weird. Does the script command do complicated things with the interpreter's output stream?

Perhaps we can automatically turn the panels back on after "script on"?
