### ISSUE TITLE
Should sometimes-secret rooms be teleportable?

### ISSUE THREAD

**Issue by mciul** [i7/kerkerkruip#412]
My test for bug #244 recently turned up something curious: Rooms like the Mausoleum and the Arcane Vault can sometimes be secret, and sometimes not. One particular random seed (1473880137) caused the Arcane Vault to be placed secretly, and then the Mausoleum to be connected to it. This caused the Mausoleum to be marked not secret.

Now, not much is done with this information other than to prevent non-secret rooms from being connected to secret rooms. But marking a room secret forces it to be non-teleportable. My question is, should marking a room as not secret cause it to become teleportable?

Additionally, should we prevent sometimes-secret rooms from being connected to secret rooms?

**Comment by curiousdannii** [comment]
I don't know what the current rules for teleportation are, but I think it would make sense for it to be limited to somewhere connected to the source room. Without that kind of restriction when either you or Malygris teleport it could make the game unfinishable if you don't have means of digging.

**Comment by mciul** [comment]
I believe that is currently true unless you have used the Rod of the Master Builder to completely separate two areas of the main dungeon.

The question relates to secret rooms that have already been discovered - if you dig to a secret room, that room becomes connected to the dungeon, but you will still never teleport there. Even if a sometimes-secret room starts out connected (and not secret), you can still never teleport there.

I asked the second question because I was confused about how this bug cropped up in the first place. Unfortunately, I didn't save the transcript from the original bug and I'm confused about how it was possible. I may have to revert to an earlier commit just to recreate the transcript.

**Comment by mciul** [comment]
Ok, going back to that old version, I see that the Mausoleum and the Arcane Vault are both secretly placeable but also connectable. That means the Arcane Vault can be secretly placed, and then the Mausoleum can be connected to it while both remain secret. So the question is: do we desire this outcome?

**Comment by mciul** [comment]
Here's the transcript from the failing test:
[fail-244.transcript.txt](https://github.com/i7/kerkerkruip/files/483501/fail-244.transcript.txt)

**Comment by mciul** [comment]
I just checked the code and it already says "normally placed" - but I think there's a bug in the definition of normally placed - a room is normally placed even when it is secretly placed!

**Comment by mciul** [comment]
I think the actual bugs here are resolved. The remaining question revolves around the definition of "teleport-receiving," which is the adjective that should always be used when choosing a teleport destination. I have updated the code to enforce this, but have not changed the definition.

**Comment by mciul** [comment]
I guess I'm happy... if you can't teleport to a tunnel then maybe it doesn't make sense to teleport to a sometimes-secret room.

**Comment by mciul** [comment]
I think I'm done with this for now. I may make a new refactoring ticket for Kerkerkruip 11.
